tasks:
  - command: |
      WelcomeFile='/workspace/GHCiCode/README.md'
      # gp open won't work until the IDE GUI is ready
      until gp open ${WelcomeFile}; do sleep 1; done
      # Safe to open more files from now on
      gp open src/app/gui-model/guimodel.ts
  - init: eval $(gp env NG_CLI_ANALYTICS=false) && npm install
    command: npm run start
ports:
  - port: 8080
    onOpen: ignore
  - port: 4200
    onOpen: open-preview
